### ISSUE TITLE
Deck Class

### ISSUE THREAD

**Issue by quac88** [quac88/ACC-CS-CLUB-ML#3]
We will use this guys implementation: https://github.com/Chippers255/Cards

**Comment by MichaelAGolden** [comment]
We fork and make changes as needed for our implementation?

**Comment by quac88** [comment]
@MichaelAGolden I was just going to copy his code and leave his name in the credits, but yea pretty much. I tested it already, and it runs pretty smoothly. Also, it is a nice and simple design.
