### ISSUE TITLE
Build the Poker module

### ISSUE THREAD

**Issue by quac88** [quac88/ACC-CS-CLUB-ML#4]
From largest object to smallest:

Game
- players, table, dealer

Table
- seats, players

Player
- name, stack, hand, status

Dealer
- deck, current_bet, pot, button

Pot
- pot

Muck
- muck

**Comment by quac88** [comment]
https://github.com/quac88/NitDestroyer/tree/quac/feat/improve-run.py

**Comment by quac88** [comment]
working from this branch ^

**Comment by MichaelAGolden** [comment]
Are there cases where a split pot will result in an number that is not divisible by the number of players? If so, what is the logic for awarding the remainder?

**Comment by quac88** [comment]
No, all the pots will always be evenly divisible. However, in future iterations of games greater than 2 people, we will need to update the split pot logic. For now this is good for rhode island holdem, but it wont hurt if one of us updates it ahead of time.
